export const GET_DATA_SOCIAL_FEED = 'GET_DATA_SOCIAL_FEED';
export const CLEAR_DATA_SOCIAL_FEED = 'CLEAR_DATA_SOCIAL_FEED';
export const TOGGLE_LOADING_INDICATOR_SOCIAL_FEED = 'TOGGLE_LOADING_INDICATOR_SOCIAL_FEED';
